version: '3.5'

services:
  target:
    container_name: nerf-touch-target
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
networks:
  default:
    external:
      name: webproxy